import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
	try {
		const res = await fetch(`${process.env.VERCEL_URL ?? "http://localhost:3000/"}/api/categories`);
		const data = await res.json();
		return {
			props: {
				categories: data,
			},
		};
	} catch (error) {
		return {
			props: {
				categories: [],
			},
		};
	}
}

export default function Home({ categories = [] }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-3xl font-bold underline">Hello world!</h1>
			{categories.map((cat) => (
				<h1 key={cat.id}>{cat.name}</h1>
			))}
		</>
	);
}
