import Head from "next/head";
import { Inter } from "@next/font/google";
import { Category } from "@prisma/client";
import { getCategories } from "@/data/categoriesData";
import { prisma } from "lib/prisma";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
	try {
		const categories = await prisma.category.findMany();
		return {
			props: {
				categories: categories,
			},
		};
	} catch (error) {
		return {
			props: { categories: null },
		};
	}
}

export default function Home({ categories = [] }: { categories: Category[] | null }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-3xl font-bold underline">Hello world!</h1>
			{/* {JSON.stringify(categories, null, 2)} */}
			{categories?.map((cat) => (
				<h1 key={cat.id}>{cat.name}</h1>
			))}
		</>
	);
}
